theme: jekyll-theme-minimal
title: Brand Score & Location Mapping Tool
description: This tool enables visualization of restaurant current locations and brand regional score indexes to identify opportunity areas for brand expansion.
